[shorturls]
channel = "https://channels.nixos.org/{path}/nixexprs.tar.xz"
rad = "git+https://rosa.radicle.network/{path}.git"

[all_follow]
crane = []
fenix = []
nixpkgs = []
rust-overlay = []

[inputs]
nixpkgs.url = "channel:nixos-unstable"
nixpkgs-xanmod.url = "github:nixos/nixpkgs?rev=d407951447dcd00442e97087bf374aad70c04cea"

nf.url = "rad:z3EZi6d3LccUz1s6UmMfuoPJfMdZ"
nixexprs.url = "github:kaktu5/nixexprs"
preservation.url = "github:kaktu5/preservation"

aagl-gtk-on-nix.url = "github:ezkea/aagl-gtk-on-nix"
cade.url = "github:manic-systems/cade"
hjem.url = "github:feel-co/hjem"
lanzaboote.url = "github:nix-community/lanzaboote"
microvm.url = "github:microvm-nix/microvm.nix"
nix-secrets.url = "github:unnamed-systems/nix-secrets"
nixos-core.url = "github:manic-systems/nixos-core"
xdg-utils-nu.url = "github:manic-systems/xdg-utils.nu"

dnscrypt-settings = {type = "fetch", url = "github:quad9dns/dnscrypt-settings"}
oisd = {type = "fetch", url = "github:sjhgvr/oisd"}
