[shorturls]
channel = "https://channels.nixos.org/{path}/nixexprs.tar.xz"

[all_follow]
crane = []
nixpkgs = ["nixpkgs-lib"]
rust-overlay = []

[inputs]
nixpkgs.url = "channel:nixos-unstable"

nixexprs.url = "github:kaktu5/nixexprs"

hjem.url = "github:feel-co/hjem"
microvm.url = "github:microvm-nix/microvm.nix"
preservation.url = "github:nix-community/preservation"
stash.url = "github:notashelf/stash"
tack.url = "github:manic-systems/tack/next"
tuigreet.url = "github:notashelf/tuigreet"
vaultix.url = "github:milieuim/vaultix"

dnscrypt-settings = {type = "fetch", url = "github:quad9dns/dnscrypt-settings"}
oisd = {type = "fetch", url = "github:sjhgvr/oisd"}
