[shorturls]
channel = "https://channels.nixos.org/{path}/nixexprs.tar.zst"
rad = "git+https://iris.radicle.network/{path}.git"

[all_follow]
fenix = []
nixpkgs = []
rust-overlay = []

[inputs]
nixpkgs = {patches = [
  "github:nixos/nixpkgs/pull/538226", # millennium
  "github:nixos/nixpkgs/pull/562711", # rhythia
], url = "channel:nixos-unstable"}

nf.url = "rad:z3EZi6d3LccUz1s6UmMfuoPJfMdZ"
nixexprs.url = "github:kaktu5/nixexprs"

aagl-gtk-on-nix = {omit_inputs = [
  "flake-compat",
], url = "github:ezkea/aagl-gtk-on-nix"}
cade.url = "github:manic-systems/cade?rev=3211f782a53f94842bbb8782de03a2c5d85c793d" # cade.url = "github:manic-systems/cade"
helium-flake.url = "github:amaanq/helium-flake"
hjem.url = "github:feel-co/hjem"
lanzaboote = {omit_inputs = [
  "pre-commit",
], url = "github:nix-community/lanzaboote"}
microvm = {omit_inputs = ["spectrum"], url = "github:microvm-nix/microvm.nix"}
nix-secrets.url = "github:unnamed-systems/nix-secrets"
nixos-core = {patches = [
  "patches/nixos-core/dont-create-home-dirs.patch",
], url = "github:manic-systems/nixos-core"}
tack.url = "github:manic-systems/tack"
xdg-utils-nu.url = "github:manic-systems/xdg-utils.nu"

dnscrypt-settings = {type = "fetch", url = "github:quad9dns/dnscrypt-settings"}
license-list-data = {type = "fetch", url = "github:spdx/license-list-data"}
oisd = {type = "fetch", url = "github:sjhgvr/oisd"}
